#ifndef _PS_TO_DCM_H
#define _PS_TO_DCM_H

#include "common.h" 

#define DCM_GRP_ID_IPMI_SYSPARAM        80000 
#define DCM_GRP_ID_IPMI_USERINFO        80001
#define DCM_GRP_ID_IPMI_LANIPCFG        80002                                                                                                                                                  
#define DCM_GRP_ID_IPMI_LANCFG          80003 
#define DCM_GRP_ID_IPMI_LANPEFCFG       80004 
#define DCM_GRP_ID_IPMI_CHASSIS         80005 
#define DCM_GRP_ID_IPMI_SDR             80006 
#define DCM_GRP_ID_IPMI_SEL             80007 
#define DCM_GRP_ID_IPMI_PEF_SELDOM      80008 
#define DCM_GRP_ID_IPMI_PEF_OFTEN       80009 
#define DCM_GRP_ID_IPMI_SER             80010 
#define DCM_GRP_ID_IPMI_SOL             80011 
#define DCM_GRP_ID_IPMI_FW              80012 
#define DCM_GRP_ID_IPMI_USER_ENCRYPT    80013 
#define DCM_GRP_ID_IPMI_PWM             80014 

typedef struct
{
    u32 u32GroupType;
    u16 u16Offset;
    u8 u8FieldIndex;
    u8 u8FieldNum;
	u16 u16EntrySize;
} sPSToDCMEntry;

const sPSToDCMEntry G_aPSToDCMTemplate[] =
{
    /*IPMI_SYSPARAM*/
    {DCM_GRP_ID_IPMI_SYSPARAM,0,1,1,0},      /*CTRL_ADDR*/
    {DCM_GRP_ID_IPMI_SYSPARAM,1,2,1,0},      /*DEVICE_GUID*/
	/*IPMI_USERINFO*/
	{DCM_GRP_ID_IPMI_USERINFO,0,1,16,USERINFOPS_ENTRY_SIZE}, 	/*USERNAME*/
	{DCM_GRP_ID_IPMI_USERINFO,17,2,16,USERINFOPS_ENTRY_SIZE},	/*USERPWD*/
	{DCM_GRP_ID_IPMI_USERINFO,39,3,16,USERINFOPS_ENTRY_SIZE},	/*USER_CHANNEL_ACCESS*/
	{DCM_GRP_ID_IPMI_USERINFO,48,4,16,USERINFOPS_ENTRY_SIZE},	/*USER_PAYLOAD_ACCESS*/
    /*IPMI_LANIPCFG*/
    {DCM_GRP_ID_IPMI_LANIPCFG,0,1,1,0},      /*LANCFG_IP*/
    {DCM_GRP_ID_IPMI_LANIPCFG,5,2,1,0},      /*LANCFG_MAC*/
    {DCM_GRP_ID_IPMI_LANIPCFG,12,3,1,0},     /*LANCFG_MISC*/
    {DCM_GRP_ID_IPMI_LANIPCFG,26,4,1,0},     /*LANCFG_DEF*/
    {DCM_GRP_ID_IPMI_LANIPCFG,37,5,1,0},     /*LANCFG_BAK*/
    /*IPMI_LANCFG*/
    {DCM_GRP_ID_IPMI_LANCFG,0,1,1,0},      /*LAN_AUTH_ENABLE*/
    {DCM_GRP_ID_IPMI_LANCFG,6,2,1,0},      /*LAN_CIPHER_SUITE_PRV*/
    {DCM_GRP_ID_IPMI_LANCFG,16,3,1,0},     /*LAN_CHANNEL_ACCESS*/
    {DCM_GRP_ID_IPMI_LANCFG,19,4,1,0},     /*LAN_SECURITY_KEY_KR*/
    {DCM_GRP_ID_IPMI_LANCFG,41,5,1,0},     /*LAN_SECURITY_KEY_KG*/
    {DCM_GRP_ID_IPMI_LANCFG,63,6,1,0},     /*LAN_CIPHER_SUITE_PRV_EX*/
    /*IPMI_LANPEFCFG*/
    {DCM_GRP_ID_IPMI_LANPEFCFG,0,1,1,0},      /*LANPEF_COMMUNITY_STR*/
    {DCM_GRP_ID_IPMI_LANPEFCFG,18,2,4,3},      /*LANPEF_DEST_TYPE*/
    {DCM_GRP_ID_IPMI_LANPEFCFG,30,3,4,12},      /*LANPEF_DEST_ADDR*/
    {DCM_GRP_ID_IPMI_LANPEFCFG,78,4,4,3},      /*LANPEF_DEST_IPV6_TYPE*/
    {DCM_GRP_ID_IPMI_LANPEFCFG,90,5,4,40},      /*LANPEF_DEST_IPV6_ADDR*/
    /*IPMI_CHASSIS*/
    {DCM_GRP_ID_IPMI_CHASSIS,0,1,1,0},      /*CHASSISDATA*/
    /*IPMI_SDR*/
    {DCM_GRP_ID_IPMI_SDR,0,1,1,0},      /*SDRDATA*/
    /*IPMI_SEL*/
    {DCM_GRP_ID_IPMI_SEL,0,1,1,0},      /*SELDATA*/
    /*IPMI_PEF_SELDOM*/
    {DCM_GRP_ID_IPMI_PEF_SELDOM,0,1,1,0},      		/*PEF_CTRL*/
    {DCM_GRP_ID_IPMI_PEF_SELDOM,1,2,1,0},      		/*PEF_GLOBAL_CTRL*/
    {DCM_GRP_ID_IPMI_PEF_SELDOM,2,3,1,0},      		/*PEF_STARTUP_DELAY*/
    {DCM_GRP_ID_IPMI_PEF_SELDOM,3,4,1,0},      		/*PEF_ALERT_STARTUP_DELAY*/    
    {DCM_GRP_ID_IPMI_PEF_SELDOM,4,5,255,20},      	/*PEF_FILTER_ENTRY*/    
    {DCM_GRP_ID_IPMI_PEF_SELDOM,5104,6,8,3},      	/*PEF_ALERT_ENTRY*/    
    {DCM_GRP_ID_IPMI_PEF_SELDOM,5128,7,1,17},      	/*PEF_SYS_GUID*/    
    {DCM_GRP_ID_IPMI_PEF_SELDOM,5145,8,8,50},      	/*PEF_ALERT_STR_ENTRY*/    
    /*IPMI_PEF_OFTEN*/
    {DCM_GRP_ID_IPMI_PEF_OFTEN,0,1,1,0},      /*SW_REC_ID*/
    {DCM_GRP_ID_IPMI_PEF_OFTEN,2,2,1,0},      /*BMC_REC_ID*/
    /*IPMI_SER*/
    {DCM_GRP_ID_IPMI_SER,0,1,1,0},      /*AUTH_TYPE_ENABLES*/
    {DCM_GRP_ID_IPMI_SER,5,2,1,0},      /*CONN_MODE*/
    {DCM_GRP_ID_IPMI_SER,6,3,1,0},      /*SESS_TIMEOUT*/
    {DCM_GRP_ID_IPMI_SER,7,4,1,0},      /*SESS_TERMINAL_TIMEOUT*/
    {DCM_GRP_ID_IPMI_SER,8,5,1,0},      /*COMMON_SETTING*/
    {DCM_GRP_ID_IPMI_SER,10,6,1,0},     /*MUX_SWITCH_CTRL*/
    {DCM_GRP_ID_IPMI_SER,12,7,1,0},     /*TERMINAL_CONFIG*/
    {DCM_GRP_ID_IPMI_SER,14,8,1,0},     /*CHANNEL_ACCESS*/
    {DCM_GRP_ID_IPMI_SER,16,9,1,0},     /*PORT_ASSOCIATION*/
    /*IPMI_SOL*/
    {DCM_GRP_ID_IPMI_SOL,0,1,1,0},      /*ENABLE_CFG*/
    {DCM_GRP_ID_IPMI_SOL,1,2,1,0},      /*AUTH*/
    {DCM_GRP_ID_IPMI_SOL,2,3,1,0},      /*CHARACTER_INFO*/
    {DCM_GRP_ID_IPMI_SOL,4,4,1,0},      /*RETRY*/
    {DCM_GRP_ID_IPMI_SOL,6,5,1,0},      /*SER_SETTING*/
	/*IPMI_FW*/
    {DCM_GRP_ID_IPMI_FW,0,1,1,0},      /*HEADER*/
    {DCM_GRP_ID_IPMI_FW,16,2,1,0},      /*CHANNEL_OFFSET*/
    {DCM_GRP_ID_IPMI_FW,32,3,8,41},      /*CHANNEL_HEADER*/
    {DCM_GRP_ID_IPMI_FW,36,4,8,41},      /*CHANNEL_ENABLE_CMD*/
    {DCM_GRP_ID_IPMI_FW,43,5,8,41},      /*CHANNEL_SUBFN_SETTING*/
    /*IPMI_USER_ENCRYPT*/
    {DCM_GRP_ID_IPMI_USER_ENCRYPT,0,1,1,0},      /*NAME_VKEY*/
    {DCM_GRP_ID_IPMI_USER_ENCRYPT,17,2,1,0},     /*NAME_KEY2*/
    {DCM_GRP_ID_IPMI_USER_ENCRYPT,34,3,1,0},     /*PWD_IVKEY*/
    {DCM_GRP_ID_IPMI_USER_ENCRYPT,51,4,1,0},     /*PWD_KEY2*/
    /*IPMI_PWM*/
    {DCM_GRP_ID_IPMI_PWM,0,1,1,0},      /*PWMDATA*/
    {0,0,0,0}
};

#endif /* _PS_TO_DCM_H */
